### ISSUE TITLE
No longer parsing placeholders?

### ISSUE THREAD

**Issue by KhaozFrost** [EpicBanItemTeam/VirtualChest#107]
```
Slot12 = [{
    Item {
        Count = 1
        ItemType = "pixelmon:hard_stone"
        UnsafeDamage = 0
        DisplayName = "&6&lMicroscopic"
        ItemLore = [
	    ""
        ]
    }
    KeepOpen = true
    PrimaryAction {
        Command = "cost: economylite:ShadowPlate:25;console: plaintell %player_name% &b&lThe Spectre &7&l> &aYou have spent &e25x &5Shadow Plates&a and received a &5Shadow &7Arceus; console: pokegive %player% arceus texture:shadow1 aura:ShadowForm nickname:&5Shadow_&r%pokemon% nummaxivs:6 ba:cherish n:adamant gr:microscopic"
        KeepInventoryOpen = false
    }
}]
```
placeholder not being parsed correctly when /pokegive is used is %pokemon%
the placeholder is handled by a customspecs plugin for the pixelmon addon and the command works correctly if ran in console or by the player but when the button is clicked; it does not work at all.

instead we get this
http://prntscr.com/ozozk1

**Comment by ustc-zzzz** [comment]
Use command `/papi parse <player> %pokemon%` to check if the papi works normally first.

**Comment by ustc-zzzz** [comment]
Closed since it is submitted several months ago. Reopen this issue if it still occurs.
