### ISSUE TITLE
items not being given when clicked.?

### ISSUE THREAD

**Issue by KhaozFrost** [EpicBanItemTeam/VirtualChest#109]
https://gyazo.com/0cc6d503dfba012cabe3fd988a3a6971
https://gyazo.com/4dd6b00db11a30c339f13e3c11b6728c
http://prntscr.com/p8wn4g

In this preview I'm giving the menu 3 gems that are being sold as a currency. then withdrawing using said currency to "give" the item back. (i'll provide the menu below) but if the player clicks multiple times (not even to quickly be it) then it just makes the item vanish.

https://gist.github.com/KhaozFrost/4c565b87547ef752544607f40d6a3528

**Comment by ustc-zzzz** [comment]
Closed since it is submitted several months ago. Reopen this issue if it still occurs.
