### ISSUE TITLE
link actions? (Request if not added)

### ISSUE THREAD

**Issue by KhaozFrost** [EpicBanItemTeam/VirtualChest#110]
I'd like to make a vote menu that when clicked on prompts opening a link. I don't want to forcefully open browser but call that precaution menu thats like "you're about to open a link" kinda thing. Not sure if its currently possible to do in vchest for opening links but if not is it possible to add?

**Comment by ustc-zzzz** [comment]
It's not possible. The behavior is limited by vanilla minecraft client that there is only one way to open a link by clicking raw texts (text jsons).
