### ISSUE TITLE
vchest action requirements?

### ISSUE THREAD

**Issue by KhaozFrost** [EpicBanItemTeam/VirtualChest#112]
Slot10 = [{
		Item {
			Count = 1
			ItemType = "minecraft:dirt"
			UnsafeDamage = 0
			DisplayName = "&f&lDirt"
			ItemLore = [
            "",
			"&aBuy Price: &l$16&r&a/each"
            "",
            "&f&m----------------------"
            "&eRight Click &7to buy&e 1",
            "&eShift + Right Click &7to buy&e 16",
			""
            "&eLeft Click &7to buy&e 32",
            "&eShift + Left Click &7to buy&e 64",
			]
		}
		KeepOpen = true
        PrimaryAction {
            Command = "cost: 16;console: give %player_name% minecraft:dirt 1"
            CommandAfter= "tell: &aYou bought &71 Dirt&a for &b$16"
            KeepInventoryOpen = true
		}
        PrimaryShiftAction {
            Command = "cost: 16;console: give %player_name% minecraft:dirt 1"
            CommandAfter= "tell: &aYou bought &71 Dirt&a for &b$16"
            KeepInventoryOpen = true
		}
        SecondaryAction {
            Command = "cost: 16;console: give %player_name% minecraft:dirt 1"
            CommandAfter= "tell: &aYou bought &71 Dirt&a for &b$16"
            KeepInventoryOpen = true
		}
        SecondaryShiftAction {
            Command = "cost: 16;console: give %player_name% minecraft:dirt 1"
            CommandAfter= "tell: &aYou bought &71 Dirt&a for &b$16"
            KeepInventoryOpen = true
		}
	}]
from the look of the wiki its not possible to apply requirements to actions directly; only the item as a whole. is there some way to make this particular item work without having to have 200+ lines per item since i have alot more items to do.

**Comment by hellbringer616** [comment]
What happens if you move `Requirements = "%economy_balance% >=  #"` to the inside of your action?

**Comment by ustc-zzzz** [comment]
It's intended. Display a same item which has no action as a fallback. Besides, you can use one `Action` instead of configuring four actions.
